#!/bin/bash

######################
# start of functions #
######################
enter_to_continue()
{
    read -n1 -s -r -p $'Press ENTER to continue...\n' key

    if [ "$key" = '' ]; then
        # ENTER pressed, do something
        # echo [$key] is empty when SPACE is pressed # uncomment to trace
    else
        # Anything else pressed, do whatever else.
        # echo [$key] not empty
    fi
}

####################
# end of functions #
####################

###################
# start of script #
###################

echo Setting timezone...
echo ===================
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
date
enter_to_continue
echo

echo Configuring locales...
echo ======================
echo 'LC_ALL=de_DE.UTF-8' >| /etc/environment
echo 'de_DE.UTF-8 UTF-8' >| /etc/locale.gen
echo 'LANG=de_DE.UTF-8' >| /etc/locale.conf
locale-gen
enter_to_continue
echo

echo Updating and configuring mirrorlist...
echo ======================================
echo Provide Pacman mirror URL.
echo !!! Only the URL, without "Server = " !!!
echo Example: https://mirror.domain.com/archlinux/$repo/os/$arch
echo Latest Mirrors: https://archlinux.org/mirrorlist/?country=all&protocol=https&ip_version=4&ip_version=6
read mirror_url
echo "Server = $mirror_url" >| /etc/pacman.d/mirrorlist
pacman-key --init
pacman-key --populate archlinux
trust extract-compat
pacman -Syy archlinux-keyring --noconfirm
pacman-key --refresh-keys
enter_to_continue
echo

echo Updating system...
echo ==================
pacman -Syyu
enter_to_continue
echo

echo =======================
echo = Rebooting system... =
echo =======================
enter_to_continue
reboot

#################
# end of script #
#################
